//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumoWsOffline.Servicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://edoc.pe/", ConfigurationName="Servicio.CoreBusinessSoap")]
    public interface CoreBusinessSoap {
        
        // CODEGEN: Generating message contract since element name RucEmpresa from namespace http://edoc.pe/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://edoc.pe/ProcesaComprobanteDirectTXT", ReplyAction="*")]
        ConsumoWsOffline.Servicio.ProcesaComprobanteDirectTXTResponse ProcesaComprobanteDirectTXT(ConsumoWsOffline.Servicio.ProcesaComprobanteDirectTXTRequest request);
        
        // CODEGEN: Generating message contract since element name RucEmpresa from namespace http://edoc.pe/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://edoc.pe/ProcesaComprobanteDirectXML", ReplyAction="*")]
        ConsumoWsOffline.Servicio.ProcesaComprobanteDirectXMLResponse ProcesaComprobanteDirectXML(ConsumoWsOffline.Servicio.ProcesaComprobanteDirectXMLRequest request);
        
        // CODEGEN: Generating message contract since element name RucEmpresa from namespace http://edoc.pe/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://edoc.pe/ProcesaComprobanteDirectSND", ReplyAction="*")]
        ConsumoWsOffline.Servicio.ProcesaComprobanteDirectSNDResponse ProcesaComprobanteDirectSND(ConsumoWsOffline.Servicio.ProcesaComprobanteDirectSNDRequest request);
        
        // CODEGEN: Generating message contract since element name RucEmpresa from namespace http://edoc.pe/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://edoc.pe/ProcesaComprobanteTicketTXT", ReplyAction="*")]
        ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTResponse ProcesaComprobanteTicketTXT(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTRequest request);
        
        // CODEGEN: Generating message contract since element name RucEmpresa from namespace http://edoc.pe/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://edoc.pe/ProcesaComprobanteTicketTXTrPDF", ReplyAction="*")]
        ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTrPDFResponse ProcesaComprobanteTicketTXTrPDF(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTrPDFRequest request);
        
        // CODEGEN: Generating message contract since element name RucEmpresa from namespace http://edoc.pe/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://edoc.pe/ProcesaComprobanteTicketXML", ReplyAction="*")]
        ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLResponse ProcesaComprobanteTicketXML(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLRequest request);
        
        // CODEGEN: Generating message contract since element name RucEmpresa from namespace http://edoc.pe/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://edoc.pe/ProcesaComprobanteTicketXMLrPDF", ReplyAction="*")]
        ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLrPDFResponse ProcesaComprobanteTicketXMLrPDF(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLrPDFRequest request);
        
        // CODEGEN: Generating message contract since element name RucEmpresa from namespace http://edoc.pe/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://edoc.pe/ProcesaComprobanteTicketSND", ReplyAction="*")]
        ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDResponse ProcesaComprobanteTicketSND(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDRequest request);
        
        // CODEGEN: Generating message contract since element name RucEmpresa from namespace http://edoc.pe/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://edoc.pe/ProcesaComprobanteTicketSNDrPDF", ReplyAction="*")]
        ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDrPDFResponse ProcesaComprobanteTicketSNDrPDF(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDrPDFRequest request);
        
        // CODEGEN: Generating message contract since element name RucEmpresa from namespace http://edoc.pe/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://edoc.pe/ObtenerEstadoComprobanteTicket", ReplyAction="*")]
        ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketResponse ObtenerEstadoComprobanteTicket(ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketRequest request);
        
        // CODEGEN: Generating message contract since element name RucEmpresa from namespace http://edoc.pe/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://edoc.pe/ObtenerEstadoComprobanteTicketPDF", ReplyAction="*")]
        ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketPDFResponse ObtenerEstadoComprobanteTicketPDF(ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketPDFRequest request);
        
        // CODEGEN: Generating message contract since element name RucEmpresa from namespace http://edoc.pe/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://edoc.pe/ObtenerPDFComprobanteTicket", ReplyAction="*")]
        ConsumoWsOffline.Servicio.ObtenerPDFComprobanteTicketResponse ObtenerPDFComprobanteTicket(ConsumoWsOffline.Servicio.ObtenerPDFComprobanteTicketRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcesaComprobanteDirectTXTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcesaComprobanteDirectTXT", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ProcesaComprobanteDirectTXTRequestBody Body;
        
        public ProcesaComprobanteDirectTXTRequest() {
        }
        
        public ProcesaComprobanteDirectTXTRequest(ConsumoWsOffline.Servicio.ProcesaComprobanteDirectTXTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ProcesaComprobanteDirectTXTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RucEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClaveAcceso;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NombreArchivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] ContenidoArchivo;
        
        public ProcesaComprobanteDirectTXTRequestBody() {
        }
        
        public ProcesaComprobanteDirectTXTRequestBody(string RucEmpresa, string ClaveAcceso, string NombreArchivo, byte[] ContenidoArchivo) {
            this.RucEmpresa = RucEmpresa;
            this.ClaveAcceso = ClaveAcceso;
            this.NombreArchivo = NombreArchivo;
            this.ContenidoArchivo = ContenidoArchivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcesaComprobanteDirectTXTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcesaComprobanteDirectTXTResponse", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ProcesaComprobanteDirectTXTResponseBody Body;
        
        public ProcesaComprobanteDirectTXTResponse() {
        }
        
        public ProcesaComprobanteDirectTXTResponse(ConsumoWsOffline.Servicio.ProcesaComprobanteDirectTXTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ProcesaComprobanteDirectTXTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ProcesaComprobanteDirectTXTResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] ContenidoArchIntegracion;
        
        public ProcesaComprobanteDirectTXTResponseBody() {
        }
        
        public ProcesaComprobanteDirectTXTResponseBody(int ProcesaComprobanteDirectTXTResult, byte[] ContenidoArchIntegracion) {
            this.ProcesaComprobanteDirectTXTResult = ProcesaComprobanteDirectTXTResult;
            this.ContenidoArchIntegracion = ContenidoArchIntegracion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcesaComprobanteDirectXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcesaComprobanteDirectXML", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ProcesaComprobanteDirectXMLRequestBody Body;
        
        public ProcesaComprobanteDirectXMLRequest() {
        }
        
        public ProcesaComprobanteDirectXMLRequest(ConsumoWsOffline.Servicio.ProcesaComprobanteDirectXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ProcesaComprobanteDirectXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RucEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClaveAcceso;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NombreArchivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] ContenidoArchivo;
        
        public ProcesaComprobanteDirectXMLRequestBody() {
        }
        
        public ProcesaComprobanteDirectXMLRequestBody(string RucEmpresa, string ClaveAcceso, string NombreArchivo, byte[] ContenidoArchivo) {
            this.RucEmpresa = RucEmpresa;
            this.ClaveAcceso = ClaveAcceso;
            this.NombreArchivo = NombreArchivo;
            this.ContenidoArchivo = ContenidoArchivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcesaComprobanteDirectXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcesaComprobanteDirectXMLResponse", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ProcesaComprobanteDirectXMLResponseBody Body;
        
        public ProcesaComprobanteDirectXMLResponse() {
        }
        
        public ProcesaComprobanteDirectXMLResponse(ConsumoWsOffline.Servicio.ProcesaComprobanteDirectXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ProcesaComprobanteDirectXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ProcesaComprobanteDirectXMLResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] ContenidoArchIntegracion;
        
        public ProcesaComprobanteDirectXMLResponseBody() {
        }
        
        public ProcesaComprobanteDirectXMLResponseBody(int ProcesaComprobanteDirectXMLResult, byte[] ContenidoArchIntegracion) {
            this.ProcesaComprobanteDirectXMLResult = ProcesaComprobanteDirectXMLResult;
            this.ContenidoArchIntegracion = ContenidoArchIntegracion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcesaComprobanteDirectSNDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcesaComprobanteDirectSND", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ProcesaComprobanteDirectSNDRequestBody Body;
        
        public ProcesaComprobanteDirectSNDRequest() {
        }
        
        public ProcesaComprobanteDirectSNDRequest(ConsumoWsOffline.Servicio.ProcesaComprobanteDirectSNDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ProcesaComprobanteDirectSNDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RucEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClaveAcceso;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NombreArchivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] ContenidoArchivo;
        
        public ProcesaComprobanteDirectSNDRequestBody() {
        }
        
        public ProcesaComprobanteDirectSNDRequestBody(string RucEmpresa, string ClaveAcceso, string NombreArchivo, byte[] ContenidoArchivo) {
            this.RucEmpresa = RucEmpresa;
            this.ClaveAcceso = ClaveAcceso;
            this.NombreArchivo = NombreArchivo;
            this.ContenidoArchivo = ContenidoArchivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcesaComprobanteDirectSNDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcesaComprobanteDirectSNDResponse", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ProcesaComprobanteDirectSNDResponseBody Body;
        
        public ProcesaComprobanteDirectSNDResponse() {
        }
        
        public ProcesaComprobanteDirectSNDResponse(ConsumoWsOffline.Servicio.ProcesaComprobanteDirectSNDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ProcesaComprobanteDirectSNDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ProcesaComprobanteDirectSNDResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] ContenidoArchIntegracion;
        
        public ProcesaComprobanteDirectSNDResponseBody() {
        }
        
        public ProcesaComprobanteDirectSNDResponseBody(int ProcesaComprobanteDirectSNDResult, byte[] ContenidoArchIntegracion) {
            this.ProcesaComprobanteDirectSNDResult = ProcesaComprobanteDirectSNDResult;
            this.ContenidoArchIntegracion = ContenidoArchIntegracion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcesaComprobanteTicketTXTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcesaComprobanteTicketTXT", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTRequestBody Body;
        
        public ProcesaComprobanteTicketTXTRequest() {
        }
        
        public ProcesaComprobanteTicketTXTRequest(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ProcesaComprobanteTicketTXTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RucEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClaveAcceso;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NombreArchivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] ContenidoArchivo;
        
        public ProcesaComprobanteTicketTXTRequestBody() {
        }
        
        public ProcesaComprobanteTicketTXTRequestBody(string RucEmpresa, string ClaveAcceso, string NombreArchivo, byte[] ContenidoArchivo) {
            this.RucEmpresa = RucEmpresa;
            this.ClaveAcceso = ClaveAcceso;
            this.NombreArchivo = NombreArchivo;
            this.ContenidoArchivo = ContenidoArchivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcesaComprobanteTicketTXTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcesaComprobanteTicketTXTResponse", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTResponseBody Body;
        
        public ProcesaComprobanteTicketTXTResponse() {
        }
        
        public ProcesaComprobanteTicketTXTResponse(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ProcesaComprobanteTicketTXTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ProcesaComprobanteTicketTXTResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NumeroTicket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ValorResumen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ValorFirma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CodigosError;
        
        public ProcesaComprobanteTicketTXTResponseBody() {
        }
        
        public ProcesaComprobanteTicketTXTResponseBody(int ProcesaComprobanteTicketTXTResult, string NumeroTicket, string ValorResumen, string ValorFirma, string CodigosError) {
            this.ProcesaComprobanteTicketTXTResult = ProcesaComprobanteTicketTXTResult;
            this.NumeroTicket = NumeroTicket;
            this.ValorResumen = ValorResumen;
            this.ValorFirma = ValorFirma;
            this.CodigosError = CodigosError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcesaComprobanteTicketTXTrPDFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcesaComprobanteTicketTXTrPDF", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTrPDFRequestBody Body;
        
        public ProcesaComprobanteTicketTXTrPDFRequest() {
        }
        
        public ProcesaComprobanteTicketTXTrPDFRequest(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTrPDFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ProcesaComprobanteTicketTXTrPDFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RucEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClaveAcceso;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NombreArchivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] ContenidoArchivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool obtenerPDF;
        
        public ProcesaComprobanteTicketTXTrPDFRequestBody() {
        }
        
        public ProcesaComprobanteTicketTXTrPDFRequestBody(string RucEmpresa, string ClaveAcceso, string NombreArchivo, byte[] ContenidoArchivo, bool obtenerPDF) {
            this.RucEmpresa = RucEmpresa;
            this.ClaveAcceso = ClaveAcceso;
            this.NombreArchivo = NombreArchivo;
            this.ContenidoArchivo = ContenidoArchivo;
            this.obtenerPDF = obtenerPDF;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcesaComprobanteTicketTXTrPDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcesaComprobanteTicketTXTrPDFResponse", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTrPDFResponseBody Body;
        
        public ProcesaComprobanteTicketTXTrPDFResponse() {
        }
        
        public ProcesaComprobanteTicketTXTrPDFResponse(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTrPDFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ProcesaComprobanteTicketTXTrPDFResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ProcesaComprobanteTicketTXTrPDFResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NumeroTicket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ValorResumen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ValorFirma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CodigosError;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] ContenidoArchPDF;
        
        public ProcesaComprobanteTicketTXTrPDFResponseBody() {
        }
        
        public ProcesaComprobanteTicketTXTrPDFResponseBody(int ProcesaComprobanteTicketTXTrPDFResult, string NumeroTicket, string ValorResumen, string ValorFirma, string CodigosError, byte[] ContenidoArchPDF) {
            this.ProcesaComprobanteTicketTXTrPDFResult = ProcesaComprobanteTicketTXTrPDFResult;
            this.NumeroTicket = NumeroTicket;
            this.ValorResumen = ValorResumen;
            this.ValorFirma = ValorFirma;
            this.CodigosError = CodigosError;
            this.ContenidoArchPDF = ContenidoArchPDF;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcesaComprobanteTicketXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcesaComprobanteTicketXML", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLRequestBody Body;
        
        public ProcesaComprobanteTicketXMLRequest() {
        }
        
        public ProcesaComprobanteTicketXMLRequest(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ProcesaComprobanteTicketXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RucEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClaveAcceso;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NombreArchivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] ContenidoArchivo;
        
        public ProcesaComprobanteTicketXMLRequestBody() {
        }
        
        public ProcesaComprobanteTicketXMLRequestBody(string RucEmpresa, string ClaveAcceso, string NombreArchivo, byte[] ContenidoArchivo) {
            this.RucEmpresa = RucEmpresa;
            this.ClaveAcceso = ClaveAcceso;
            this.NombreArchivo = NombreArchivo;
            this.ContenidoArchivo = ContenidoArchivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcesaComprobanteTicketXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcesaComprobanteTicketXMLResponse", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLResponseBody Body;
        
        public ProcesaComprobanteTicketXMLResponse() {
        }
        
        public ProcesaComprobanteTicketXMLResponse(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ProcesaComprobanteTicketXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ProcesaComprobanteTicketXMLResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NumeroTicket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ValorResumen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ValorFirma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CodigosError;
        
        public ProcesaComprobanteTicketXMLResponseBody() {
        }
        
        public ProcesaComprobanteTicketXMLResponseBody(int ProcesaComprobanteTicketXMLResult, string NumeroTicket, string ValorResumen, string ValorFirma, string CodigosError) {
            this.ProcesaComprobanteTicketXMLResult = ProcesaComprobanteTicketXMLResult;
            this.NumeroTicket = NumeroTicket;
            this.ValorResumen = ValorResumen;
            this.ValorFirma = ValorFirma;
            this.CodigosError = CodigosError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcesaComprobanteTicketXMLrPDFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcesaComprobanteTicketXMLrPDF", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLrPDFRequestBody Body;
        
        public ProcesaComprobanteTicketXMLrPDFRequest() {
        }
        
        public ProcesaComprobanteTicketXMLrPDFRequest(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLrPDFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ProcesaComprobanteTicketXMLrPDFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RucEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClaveAcceso;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NombreArchivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] ContenidoArchivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool obtenerPDF;
        
        public ProcesaComprobanteTicketXMLrPDFRequestBody() {
        }
        
        public ProcesaComprobanteTicketXMLrPDFRequestBody(string RucEmpresa, string ClaveAcceso, string NombreArchivo, byte[] ContenidoArchivo, bool obtenerPDF) {
            this.RucEmpresa = RucEmpresa;
            this.ClaveAcceso = ClaveAcceso;
            this.NombreArchivo = NombreArchivo;
            this.ContenidoArchivo = ContenidoArchivo;
            this.obtenerPDF = obtenerPDF;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcesaComprobanteTicketXMLrPDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcesaComprobanteTicketXMLrPDFResponse", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLrPDFResponseBody Body;
        
        public ProcesaComprobanteTicketXMLrPDFResponse() {
        }
        
        public ProcesaComprobanteTicketXMLrPDFResponse(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLrPDFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ProcesaComprobanteTicketXMLrPDFResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ProcesaComprobanteTicketXMLrPDFResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NumeroTicket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ValorResumen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ValorFirma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CodigosError;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] ContenidoArchPDF;
        
        public ProcesaComprobanteTicketXMLrPDFResponseBody() {
        }
        
        public ProcesaComprobanteTicketXMLrPDFResponseBody(int ProcesaComprobanteTicketXMLrPDFResult, string NumeroTicket, string ValorResumen, string ValorFirma, string CodigosError, byte[] ContenidoArchPDF) {
            this.ProcesaComprobanteTicketXMLrPDFResult = ProcesaComprobanteTicketXMLrPDFResult;
            this.NumeroTicket = NumeroTicket;
            this.ValorResumen = ValorResumen;
            this.ValorFirma = ValorFirma;
            this.CodigosError = CodigosError;
            this.ContenidoArchPDF = ContenidoArchPDF;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcesaComprobanteTicketSNDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcesaComprobanteTicketSND", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDRequestBody Body;
        
        public ProcesaComprobanteTicketSNDRequest() {
        }
        
        public ProcesaComprobanteTicketSNDRequest(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ProcesaComprobanteTicketSNDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RucEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClaveAcceso;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NombreArchivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] ContenidoArchivo;
        
        public ProcesaComprobanteTicketSNDRequestBody() {
        }
        
        public ProcesaComprobanteTicketSNDRequestBody(string RucEmpresa, string ClaveAcceso, string NombreArchivo, byte[] ContenidoArchivo) {
            this.RucEmpresa = RucEmpresa;
            this.ClaveAcceso = ClaveAcceso;
            this.NombreArchivo = NombreArchivo;
            this.ContenidoArchivo = ContenidoArchivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcesaComprobanteTicketSNDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcesaComprobanteTicketSNDResponse", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDResponseBody Body;
        
        public ProcesaComprobanteTicketSNDResponse() {
        }
        
        public ProcesaComprobanteTicketSNDResponse(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ProcesaComprobanteTicketSNDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ProcesaComprobanteTicketSNDResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NumeroTicket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ValorResumen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ValorFirma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CodigosError;
        
        public ProcesaComprobanteTicketSNDResponseBody() {
        }
        
        public ProcesaComprobanteTicketSNDResponseBody(int ProcesaComprobanteTicketSNDResult, string NumeroTicket, string ValorResumen, string ValorFirma, string CodigosError) {
            this.ProcesaComprobanteTicketSNDResult = ProcesaComprobanteTicketSNDResult;
            this.NumeroTicket = NumeroTicket;
            this.ValorResumen = ValorResumen;
            this.ValorFirma = ValorFirma;
            this.CodigosError = CodigosError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcesaComprobanteTicketSNDrPDFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcesaComprobanteTicketSNDrPDF", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDrPDFRequestBody Body;
        
        public ProcesaComprobanteTicketSNDrPDFRequest() {
        }
        
        public ProcesaComprobanteTicketSNDrPDFRequest(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDrPDFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ProcesaComprobanteTicketSNDrPDFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RucEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClaveAcceso;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NombreArchivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] ContenidoArchivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool obtenerPDF;
        
        public ProcesaComprobanteTicketSNDrPDFRequestBody() {
        }
        
        public ProcesaComprobanteTicketSNDrPDFRequestBody(string RucEmpresa, string ClaveAcceso, string NombreArchivo, byte[] ContenidoArchivo, bool obtenerPDF) {
            this.RucEmpresa = RucEmpresa;
            this.ClaveAcceso = ClaveAcceso;
            this.NombreArchivo = NombreArchivo;
            this.ContenidoArchivo = ContenidoArchivo;
            this.obtenerPDF = obtenerPDF;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcesaComprobanteTicketSNDrPDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcesaComprobanteTicketSNDrPDFResponse", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDrPDFResponseBody Body;
        
        public ProcesaComprobanteTicketSNDrPDFResponse() {
        }
        
        public ProcesaComprobanteTicketSNDrPDFResponse(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDrPDFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ProcesaComprobanteTicketSNDrPDFResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ProcesaComprobanteTicketSNDrPDFResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NumeroTicket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ValorResumen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ValorFirma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CodigosError;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] ContenidoArchPDF;
        
        public ProcesaComprobanteTicketSNDrPDFResponseBody() {
        }
        
        public ProcesaComprobanteTicketSNDrPDFResponseBody(int ProcesaComprobanteTicketSNDrPDFResult, string NumeroTicket, string ValorResumen, string ValorFirma, string CodigosError, byte[] ContenidoArchPDF) {
            this.ProcesaComprobanteTicketSNDrPDFResult = ProcesaComprobanteTicketSNDrPDFResult;
            this.NumeroTicket = NumeroTicket;
            this.ValorResumen = ValorResumen;
            this.ValorFirma = ValorFirma;
            this.CodigosError = CodigosError;
            this.ContenidoArchPDF = ContenidoArchPDF;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerEstadoComprobanteTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerEstadoComprobanteTicket", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketRequestBody Body;
        
        public ObtenerEstadoComprobanteTicketRequest() {
        }
        
        public ObtenerEstadoComprobanteTicketRequest(ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ObtenerEstadoComprobanteTicketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RucEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClaveAcceso;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NumeroTicket;
        
        public ObtenerEstadoComprobanteTicketRequestBody() {
        }
        
        public ObtenerEstadoComprobanteTicketRequestBody(string RucEmpresa, string ClaveAcceso, string NumeroTicket) {
            this.RucEmpresa = RucEmpresa;
            this.ClaveAcceso = ClaveAcceso;
            this.NumeroTicket = NumeroTicket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerEstadoComprobanteTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerEstadoComprobanteTicketResponse", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketResponseBody Body;
        
        public ObtenerEstadoComprobanteTicketResponse() {
        }
        
        public ObtenerEstadoComprobanteTicketResponse(ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ObtenerEstadoComprobanteTicketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ObtenerEstadoComprobanteTicketResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] ContenidoArchIntegracion;
        
        public ObtenerEstadoComprobanteTicketResponseBody() {
        }
        
        public ObtenerEstadoComprobanteTicketResponseBody(int ObtenerEstadoComprobanteTicketResult, byte[] ContenidoArchIntegracion) {
            this.ObtenerEstadoComprobanteTicketResult = ObtenerEstadoComprobanteTicketResult;
            this.ContenidoArchIntegracion = ContenidoArchIntegracion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerEstadoComprobanteTicketPDFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerEstadoComprobanteTicketPDF", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketPDFRequestBody Body;
        
        public ObtenerEstadoComprobanteTicketPDFRequest() {
        }
        
        public ObtenerEstadoComprobanteTicketPDFRequest(ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketPDFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ObtenerEstadoComprobanteTicketPDFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RucEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClaveAcceso;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal pvIdApp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NumeroTicket;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool ObtenerPDF;
        
        public ObtenerEstadoComprobanteTicketPDFRequestBody() {
        }
        
        public ObtenerEstadoComprobanteTicketPDFRequestBody(string RucEmpresa, string ClaveAcceso, decimal pvIdApp, string NumeroTicket, bool ObtenerPDF) {
            this.RucEmpresa = RucEmpresa;
            this.ClaveAcceso = ClaveAcceso;
            this.pvIdApp = pvIdApp;
            this.NumeroTicket = NumeroTicket;
            this.ObtenerPDF = ObtenerPDF;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerEstadoComprobanteTicketPDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerEstadoComprobanteTicketPDFResponse", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketPDFResponseBody Body;
        
        public ObtenerEstadoComprobanteTicketPDFResponse() {
        }
        
        public ObtenerEstadoComprobanteTicketPDFResponse(ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketPDFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ObtenerEstadoComprobanteTicketPDFResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ObtenerEstadoComprobanteTicketPDFResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] ContenidoArchIntegracion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] ContenidoArchPDF;
        
        public ObtenerEstadoComprobanteTicketPDFResponseBody() {
        }
        
        public ObtenerEstadoComprobanteTicketPDFResponseBody(int ObtenerEstadoComprobanteTicketPDFResult, byte[] ContenidoArchIntegracion, byte[] ContenidoArchPDF) {
            this.ObtenerEstadoComprobanteTicketPDFResult = ObtenerEstadoComprobanteTicketPDFResult;
            this.ContenidoArchIntegracion = ContenidoArchIntegracion;
            this.ContenidoArchPDF = ContenidoArchPDF;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPDFComprobanteTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPDFComprobanteTicket", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ObtenerPDFComprobanteTicketRequestBody Body;
        
        public ObtenerPDFComprobanteTicketRequest() {
        }
        
        public ObtenerPDFComprobanteTicketRequest(ConsumoWsOffline.Servicio.ObtenerPDFComprobanteTicketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ObtenerPDFComprobanteTicketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RucEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClaveAcceso;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal pvIdApp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NumeroTicket;
        
        public ObtenerPDFComprobanteTicketRequestBody() {
        }
        
        public ObtenerPDFComprobanteTicketRequestBody(string RucEmpresa, string ClaveAcceso, decimal pvIdApp, string NumeroTicket) {
            this.RucEmpresa = RucEmpresa;
            this.ClaveAcceso = ClaveAcceso;
            this.pvIdApp = pvIdApp;
            this.NumeroTicket = NumeroTicket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPDFComprobanteTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPDFComprobanteTicketResponse", Namespace="http://edoc.pe/", Order=0)]
        public ConsumoWsOffline.Servicio.ObtenerPDFComprobanteTicketResponseBody Body;
        
        public ObtenerPDFComprobanteTicketResponse() {
        }
        
        public ObtenerPDFComprobanteTicketResponse(ConsumoWsOffline.Servicio.ObtenerPDFComprobanteTicketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edoc.pe/")]
    public partial class ObtenerPDFComprobanteTicketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ObtenerPDFComprobanteTicketResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] ContenidoArchPDF;
        
        public ObtenerPDFComprobanteTicketResponseBody() {
        }
        
        public ObtenerPDFComprobanteTicketResponseBody(int ObtenerPDFComprobanteTicketResult, byte[] ContenidoArchPDF) {
            this.ObtenerPDFComprobanteTicketResult = ObtenerPDFComprobanteTicketResult;
            this.ContenidoArchPDF = ContenidoArchPDF;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CoreBusinessSoapChannel : ConsumoWsOffline.Servicio.CoreBusinessSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoreBusinessSoapClient : System.ServiceModel.ClientBase<ConsumoWsOffline.Servicio.CoreBusinessSoap>, ConsumoWsOffline.Servicio.CoreBusinessSoap {
        
        public CoreBusinessSoapClient() {
        }
        
        public CoreBusinessSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoreBusinessSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreBusinessSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreBusinessSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWsOffline.Servicio.ProcesaComprobanteDirectTXTResponse ConsumoWsOffline.Servicio.CoreBusinessSoap.ProcesaComprobanteDirectTXT(ConsumoWsOffline.Servicio.ProcesaComprobanteDirectTXTRequest request) {
            return base.Channel.ProcesaComprobanteDirectTXT(request);
        }
        
        public int ProcesaComprobanteDirectTXT(string RucEmpresa, string ClaveAcceso, string NombreArchivo, byte[] ContenidoArchivo, out byte[] ContenidoArchIntegracion) {
            ConsumoWsOffline.Servicio.ProcesaComprobanteDirectTXTRequest inValue = new ConsumoWsOffline.Servicio.ProcesaComprobanteDirectTXTRequest();
            inValue.Body = new ConsumoWsOffline.Servicio.ProcesaComprobanteDirectTXTRequestBody();
            inValue.Body.RucEmpresa = RucEmpresa;
            inValue.Body.ClaveAcceso = ClaveAcceso;
            inValue.Body.NombreArchivo = NombreArchivo;
            inValue.Body.ContenidoArchivo = ContenidoArchivo;
            ConsumoWsOffline.Servicio.ProcesaComprobanteDirectTXTResponse retVal = ((ConsumoWsOffline.Servicio.CoreBusinessSoap)(this)).ProcesaComprobanteDirectTXT(inValue);
            ContenidoArchIntegracion = retVal.Body.ContenidoArchIntegracion;
            return retVal.Body.ProcesaComprobanteDirectTXTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWsOffline.Servicio.ProcesaComprobanteDirectXMLResponse ConsumoWsOffline.Servicio.CoreBusinessSoap.ProcesaComprobanteDirectXML(ConsumoWsOffline.Servicio.ProcesaComprobanteDirectXMLRequest request) {
            return base.Channel.ProcesaComprobanteDirectXML(request);
        }
        
        public int ProcesaComprobanteDirectXML(string RucEmpresa, string ClaveAcceso, string NombreArchivo, byte[] ContenidoArchivo, out byte[] ContenidoArchIntegracion) {
            ConsumoWsOffline.Servicio.ProcesaComprobanteDirectXMLRequest inValue = new ConsumoWsOffline.Servicio.ProcesaComprobanteDirectXMLRequest();
            inValue.Body = new ConsumoWsOffline.Servicio.ProcesaComprobanteDirectXMLRequestBody();
            inValue.Body.RucEmpresa = RucEmpresa;
            inValue.Body.ClaveAcceso = ClaveAcceso;
            inValue.Body.NombreArchivo = NombreArchivo;
            inValue.Body.ContenidoArchivo = ContenidoArchivo;
            ConsumoWsOffline.Servicio.ProcesaComprobanteDirectXMLResponse retVal = ((ConsumoWsOffline.Servicio.CoreBusinessSoap)(this)).ProcesaComprobanteDirectXML(inValue);
            ContenidoArchIntegracion = retVal.Body.ContenidoArchIntegracion;
            return retVal.Body.ProcesaComprobanteDirectXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWsOffline.Servicio.ProcesaComprobanteDirectSNDResponse ConsumoWsOffline.Servicio.CoreBusinessSoap.ProcesaComprobanteDirectSND(ConsumoWsOffline.Servicio.ProcesaComprobanteDirectSNDRequest request) {
            return base.Channel.ProcesaComprobanteDirectSND(request);
        }
        
        public int ProcesaComprobanteDirectSND(string RucEmpresa, string ClaveAcceso, string NombreArchivo, byte[] ContenidoArchivo, out byte[] ContenidoArchIntegracion) {
            ConsumoWsOffline.Servicio.ProcesaComprobanteDirectSNDRequest inValue = new ConsumoWsOffline.Servicio.ProcesaComprobanteDirectSNDRequest();
            inValue.Body = new ConsumoWsOffline.Servicio.ProcesaComprobanteDirectSNDRequestBody();
            inValue.Body.RucEmpresa = RucEmpresa;
            inValue.Body.ClaveAcceso = ClaveAcceso;
            inValue.Body.NombreArchivo = NombreArchivo;
            inValue.Body.ContenidoArchivo = ContenidoArchivo;
            ConsumoWsOffline.Servicio.ProcesaComprobanteDirectSNDResponse retVal = ((ConsumoWsOffline.Servicio.CoreBusinessSoap)(this)).ProcesaComprobanteDirectSND(inValue);
            ContenidoArchIntegracion = retVal.Body.ContenidoArchIntegracion;
            return retVal.Body.ProcesaComprobanteDirectSNDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTResponse ConsumoWsOffline.Servicio.CoreBusinessSoap.ProcesaComprobanteTicketTXT(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTRequest request) {
            return base.Channel.ProcesaComprobanteTicketTXT(request);
        }
        
        public int ProcesaComprobanteTicketTXT(string RucEmpresa, string ClaveAcceso, string NombreArchivo, byte[] ContenidoArchivo, out string NumeroTicket, out string ValorResumen, out string ValorFirma, out string CodigosError) {
            ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTRequest inValue = new ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTRequest();
            inValue.Body = new ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTRequestBody();
            inValue.Body.RucEmpresa = RucEmpresa;
            inValue.Body.ClaveAcceso = ClaveAcceso;
            inValue.Body.NombreArchivo = NombreArchivo;
            inValue.Body.ContenidoArchivo = ContenidoArchivo;
            ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTResponse retVal = ((ConsumoWsOffline.Servicio.CoreBusinessSoap)(this)).ProcesaComprobanteTicketTXT(inValue);
            NumeroTicket = retVal.Body.NumeroTicket;
            ValorResumen = retVal.Body.ValorResumen;
            ValorFirma = retVal.Body.ValorFirma;
            CodigosError = retVal.Body.CodigosError;
            return retVal.Body.ProcesaComprobanteTicketTXTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTrPDFResponse ConsumoWsOffline.Servicio.CoreBusinessSoap.ProcesaComprobanteTicketTXTrPDF(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTrPDFRequest request) {
            return base.Channel.ProcesaComprobanteTicketTXTrPDF(request);
        }
        
        public int ProcesaComprobanteTicketTXTrPDF(string RucEmpresa, string ClaveAcceso, string NombreArchivo, byte[] ContenidoArchivo, bool obtenerPDF, out string NumeroTicket, out string ValorResumen, out string ValorFirma, out string CodigosError, out byte[] ContenidoArchPDF) {
            ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTrPDFRequest inValue = new ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTrPDFRequest();
            inValue.Body = new ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTrPDFRequestBody();
            inValue.Body.RucEmpresa = RucEmpresa;
            inValue.Body.ClaveAcceso = ClaveAcceso;
            inValue.Body.NombreArchivo = NombreArchivo;
            inValue.Body.ContenidoArchivo = ContenidoArchivo;
            inValue.Body.obtenerPDF = obtenerPDF;
            ConsumoWsOffline.Servicio.ProcesaComprobanteTicketTXTrPDFResponse retVal = ((ConsumoWsOffline.Servicio.CoreBusinessSoap)(this)).ProcesaComprobanteTicketTXTrPDF(inValue);
            NumeroTicket = retVal.Body.NumeroTicket;
            ValorResumen = retVal.Body.ValorResumen;
            ValorFirma = retVal.Body.ValorFirma;
            CodigosError = retVal.Body.CodigosError;
            ContenidoArchPDF = retVal.Body.ContenidoArchPDF;
            return retVal.Body.ProcesaComprobanteTicketTXTrPDFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLResponse ConsumoWsOffline.Servicio.CoreBusinessSoap.ProcesaComprobanteTicketXML(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLRequest request) {
            return base.Channel.ProcesaComprobanteTicketXML(request);
        }
        
        public int ProcesaComprobanteTicketXML(string RucEmpresa, string ClaveAcceso, string NombreArchivo, byte[] ContenidoArchivo, out string NumeroTicket, out string ValorResumen, out string ValorFirma, out string CodigosError) {
            ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLRequest inValue = new ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLRequest();
            inValue.Body = new ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLRequestBody();
            inValue.Body.RucEmpresa = RucEmpresa;
            inValue.Body.ClaveAcceso = ClaveAcceso;
            inValue.Body.NombreArchivo = NombreArchivo;
            inValue.Body.ContenidoArchivo = ContenidoArchivo;
            ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLResponse retVal = ((ConsumoWsOffline.Servicio.CoreBusinessSoap)(this)).ProcesaComprobanteTicketXML(inValue);
            NumeroTicket = retVal.Body.NumeroTicket;
            ValorResumen = retVal.Body.ValorResumen;
            ValorFirma = retVal.Body.ValorFirma;
            CodigosError = retVal.Body.CodigosError;
            return retVal.Body.ProcesaComprobanteTicketXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLrPDFResponse ConsumoWsOffline.Servicio.CoreBusinessSoap.ProcesaComprobanteTicketXMLrPDF(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLrPDFRequest request) {
            return base.Channel.ProcesaComprobanteTicketXMLrPDF(request);
        }
        
        public int ProcesaComprobanteTicketXMLrPDF(string RucEmpresa, string ClaveAcceso, string NombreArchivo, byte[] ContenidoArchivo, bool obtenerPDF, out string NumeroTicket, out string ValorResumen, out string ValorFirma, out string CodigosError, out byte[] ContenidoArchPDF) {
            ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLrPDFRequest inValue = new ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLrPDFRequest();
            inValue.Body = new ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLrPDFRequestBody();
            inValue.Body.RucEmpresa = RucEmpresa;
            inValue.Body.ClaveAcceso = ClaveAcceso;
            inValue.Body.NombreArchivo = NombreArchivo;
            inValue.Body.ContenidoArchivo = ContenidoArchivo;
            inValue.Body.obtenerPDF = obtenerPDF;
            ConsumoWsOffline.Servicio.ProcesaComprobanteTicketXMLrPDFResponse retVal = ((ConsumoWsOffline.Servicio.CoreBusinessSoap)(this)).ProcesaComprobanteTicketXMLrPDF(inValue);
            NumeroTicket = retVal.Body.NumeroTicket;
            ValorResumen = retVal.Body.ValorResumen;
            ValorFirma = retVal.Body.ValorFirma;
            CodigosError = retVal.Body.CodigosError;
            ContenidoArchPDF = retVal.Body.ContenidoArchPDF;
            return retVal.Body.ProcesaComprobanteTicketXMLrPDFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDResponse ConsumoWsOffline.Servicio.CoreBusinessSoap.ProcesaComprobanteTicketSND(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDRequest request) {
            return base.Channel.ProcesaComprobanteTicketSND(request);
        }
        
        public int ProcesaComprobanteTicketSND(string RucEmpresa, string ClaveAcceso, string NombreArchivo, byte[] ContenidoArchivo, out string NumeroTicket, out string ValorResumen, out string ValorFirma, out string CodigosError) {
            ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDRequest inValue = new ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDRequest();
            inValue.Body = new ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDRequestBody();
            inValue.Body.RucEmpresa = RucEmpresa;
            inValue.Body.ClaveAcceso = ClaveAcceso;
            inValue.Body.NombreArchivo = NombreArchivo;
            inValue.Body.ContenidoArchivo = ContenidoArchivo;
            ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDResponse retVal = ((ConsumoWsOffline.Servicio.CoreBusinessSoap)(this)).ProcesaComprobanteTicketSND(inValue);
            NumeroTicket = retVal.Body.NumeroTicket;
            ValorResumen = retVal.Body.ValorResumen;
            ValorFirma = retVal.Body.ValorFirma;
            CodigosError = retVal.Body.CodigosError;
            return retVal.Body.ProcesaComprobanteTicketSNDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDrPDFResponse ConsumoWsOffline.Servicio.CoreBusinessSoap.ProcesaComprobanteTicketSNDrPDF(ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDrPDFRequest request) {
            return base.Channel.ProcesaComprobanteTicketSNDrPDF(request);
        }
        
        public int ProcesaComprobanteTicketSNDrPDF(string RucEmpresa, string ClaveAcceso, string NombreArchivo, byte[] ContenidoArchivo, bool obtenerPDF, out string NumeroTicket, out string ValorResumen, out string ValorFirma, out string CodigosError, out byte[] ContenidoArchPDF) {
            ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDrPDFRequest inValue = new ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDrPDFRequest();
            inValue.Body = new ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDrPDFRequestBody();
            inValue.Body.RucEmpresa = RucEmpresa;
            inValue.Body.ClaveAcceso = ClaveAcceso;
            inValue.Body.NombreArchivo = NombreArchivo;
            inValue.Body.ContenidoArchivo = ContenidoArchivo;
            inValue.Body.obtenerPDF = obtenerPDF;
            ConsumoWsOffline.Servicio.ProcesaComprobanteTicketSNDrPDFResponse retVal = ((ConsumoWsOffline.Servicio.CoreBusinessSoap)(this)).ProcesaComprobanteTicketSNDrPDF(inValue);
            NumeroTicket = retVal.Body.NumeroTicket;
            ValorResumen = retVal.Body.ValorResumen;
            ValorFirma = retVal.Body.ValorFirma;
            CodigosError = retVal.Body.CodigosError;
            ContenidoArchPDF = retVal.Body.ContenidoArchPDF;
            return retVal.Body.ProcesaComprobanteTicketSNDrPDFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketResponse ConsumoWsOffline.Servicio.CoreBusinessSoap.ObtenerEstadoComprobanteTicket(ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketRequest request) {
            return base.Channel.ObtenerEstadoComprobanteTicket(request);
        }
        
        public int ObtenerEstadoComprobanteTicket(string RucEmpresa, string ClaveAcceso, string NumeroTicket, out byte[] ContenidoArchIntegracion) {
            ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketRequest inValue = new ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketRequest();
            inValue.Body = new ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketRequestBody();
            inValue.Body.RucEmpresa = RucEmpresa;
            inValue.Body.ClaveAcceso = ClaveAcceso;
            inValue.Body.NumeroTicket = NumeroTicket;
            ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketResponse retVal = ((ConsumoWsOffline.Servicio.CoreBusinessSoap)(this)).ObtenerEstadoComprobanteTicket(inValue);
            ContenidoArchIntegracion = retVal.Body.ContenidoArchIntegracion;
            return retVal.Body.ObtenerEstadoComprobanteTicketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketPDFResponse ConsumoWsOffline.Servicio.CoreBusinessSoap.ObtenerEstadoComprobanteTicketPDF(ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketPDFRequest request) {
            return base.Channel.ObtenerEstadoComprobanteTicketPDF(request);
        }
        
        public int ObtenerEstadoComprobanteTicketPDF(string RucEmpresa, string ClaveAcceso, decimal pvIdApp, string NumeroTicket, bool ObtenerPDF, out byte[] ContenidoArchIntegracion, out byte[] ContenidoArchPDF) {
            ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketPDFRequest inValue = new ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketPDFRequest();
            inValue.Body = new ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketPDFRequestBody();
            inValue.Body.RucEmpresa = RucEmpresa;
            inValue.Body.ClaveAcceso = ClaveAcceso;
            inValue.Body.pvIdApp = pvIdApp;
            inValue.Body.NumeroTicket = NumeroTicket;
            inValue.Body.ObtenerPDF = ObtenerPDF;
            ConsumoWsOffline.Servicio.ObtenerEstadoComprobanteTicketPDFResponse retVal = ((ConsumoWsOffline.Servicio.CoreBusinessSoap)(this)).ObtenerEstadoComprobanteTicketPDF(inValue);
            ContenidoArchIntegracion = retVal.Body.ContenidoArchIntegracion;
            ContenidoArchPDF = retVal.Body.ContenidoArchPDF;
            return retVal.Body.ObtenerEstadoComprobanteTicketPDFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoWsOffline.Servicio.ObtenerPDFComprobanteTicketResponse ConsumoWsOffline.Servicio.CoreBusinessSoap.ObtenerPDFComprobanteTicket(ConsumoWsOffline.Servicio.ObtenerPDFComprobanteTicketRequest request) {
            return base.Channel.ObtenerPDFComprobanteTicket(request);
        }
        
        public int ObtenerPDFComprobanteTicket(string RucEmpresa, string ClaveAcceso, decimal pvIdApp, string NumeroTicket, out byte[] ContenidoArchPDF) {
            ConsumoWsOffline.Servicio.ObtenerPDFComprobanteTicketRequest inValue = new ConsumoWsOffline.Servicio.ObtenerPDFComprobanteTicketRequest();
            inValue.Body = new ConsumoWsOffline.Servicio.ObtenerPDFComprobanteTicketRequestBody();
            inValue.Body.RucEmpresa = RucEmpresa;
            inValue.Body.ClaveAcceso = ClaveAcceso;
            inValue.Body.pvIdApp = pvIdApp;
            inValue.Body.NumeroTicket = NumeroTicket;
            ConsumoWsOffline.Servicio.ObtenerPDFComprobanteTicketResponse retVal = ((ConsumoWsOffline.Servicio.CoreBusinessSoap)(this)).ObtenerPDFComprobanteTicket(inValue);
            ContenidoArchPDF = retVal.Body.ContenidoArchPDF;
            return retVal.Body.ObtenerPDFComprobanteTicketResult;
        }
    }
}
